# Generated by Django 3.1.3 on 2020-11-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201124_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
