# Generated by Django 3.1.3 on 2020-11-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customer'),
        ),
    ]
