# Generated by Django 3.1.3 on 2020-11-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201124_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
