# Generated by Django 3.1.3 on 2020-11-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_customer_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tags',
        ),
    ]
