# Generated by Django 3.1.3 on 2020-11-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_vendor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='seller',
        ),
    ]
