# Generated by Django 3.1.3 on 2020-11-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201124_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='vendor',
        ),
    ]
