# Generated by Django 3.1.3 on 2020-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
