# Generated by Django 3.1.3 on 2020-12-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20201201_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
